### ISSUE TITLE
Nedostupné nové obsahy

### ISSUE THREAD

**Issue by OgDInstant** [techlib/toc#10]
U nových obsahů chyba java.lang.NullPointerException, u starých se ukazuje, nevím kde je problém?

![toc_good](https://user-images.githubusercontent.com/15325058/106251614-7ca5ad80-6215-11eb-9c29-5bcd60724d77.jpg)
![toc_error](https://user-images.githubusercontent.com/15325058/106251760-ac54b580-6215-11eb-8a1f-1e067809c1fe.jpg)

**Comment by jdobiasovsky** [comment]
Výpis z logu:
```
29-Jan-2021 14:09:51.458 SEVERE [http-nio-8082-exec-6] cz.incad.ntk.toc_ntk.XServer.find error getting info from xser                                                                                                                        ver for 26446804
29-Jan-2021 14:09:51.459 SEVERE [http-nio-8082-exec-6] cz.incad.ntk.toc_ntk.XServer.find null
 org.json.JSONException: JSONObject["record"] not found.
        at org.json.JSONObject.get(JSONObject.java:473)
        at org.json.JSONObject.getJSONObject(JSONObject.java:573)
        at cz.incad.ntk.toc_ntk.XServer.find(XServer.java:29)
        at cz.incad.ntk.toc_ntk.CandidatesServlet$Actions$11.doPerform(CandidatesServlet.java:265)
        at cz.incad.ntk.toc_ntk.CandidatesServlet.processRequest(CandidatesServlet.java:47)
        at cz.incad.ntk.toc_ntk.CandidatesServlet.doGet(CandidatesServlet.java:313)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

29-Jan-2021 14:09:51.460 SEVERE [http-nio-8082-exec-6] cz.incad.ntk.toc_ntk.CandidatesServlet$Actions$11.doPerform nu                                                                                                                        ll
 java.lang.NullPointerException
        at cz.incad.ntk.toc_ntk.TocAnalizer.setLang(TocAnalizer.java:380)
        at cz.incad.ntk.toc_ntk.TocAnalizer.analyzeFolder(TocAnalizer.java:349)
        at cz.incad.ntk.toc_ntk.CandidatesServlet$Actions$11.doPerform(CandidatesServlet.java:269)
        at cz.incad.ntk.toc_ntk.CandidatesServlet.processRequest(CandidatesServlet.java:47)
        at cz.incad.ntk.toc_ntk.CandidatesServlet.doGet(CandidatesServlet.java:313)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:504)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:650)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
```

Jestli to dobře čtu tak se nedaří získat údaje z alephího xServeru:
`      String url = Options.getInstance().getString("xserver", "http://aleph.techlib.cz/X?op=find-doc&base=stk01");
      InputStream inputStream = RESTHelper.inputStream(url + "&doc_num=" + sysno);`

Takže je potřeba zjistit proč se tam propisují špatná sysna

**Comment by jdobiasovsky** [comment]
Chyba je u nás na vstupu, začali jsme v dané složce zpracovávat i časopisy, které mají obálky označené ne systémovým číslem ale ISSN, které ale cz.incad.ntk.toc_ntk.Options.getFolders() bere taky na základě pravidla že sysno je nazev jedineho existujici .jpg souboru. 

 https://github.com/techlib/toc/blob/1d426547c2fcf74e2629f99f101ac435dd17009d/toc_ntk/src/main/java/cz/incad/ntk/toc_ntk/Options.java#L88-L129
 
 Odladíme si to u nás, jenom poprosím bylo by možné přidat do výběru složek filtr, který by buď špatně pojmenované jpeg soubory ignoroval nebo chybovou hlášku že se jedná o nevalidní systémové číslo? 
 
 Napadá mě změnit: https://github.com/techlib/toc/blob/1d426547c2fcf74e2629f99f101ac435dd17009d/toc_ntk/src/main/java/cz/incad/ntk/toc_ntk/Options.java#L120
 
 Na `(sysno != null && sysno.length() == 9)`

**Comment by albertoh** [comment]
Zmenil jsem Options podle navrhu. Nevalidni slozky jsou filtrovane, a nevalidni se objevujou v logu tomcatu

**Comment by OgDInstant** [comment]
Vypadá to funkčně kolega otestoval a je spokojený, uzavírám.
